import type { FastifyInstance } from "fastify";
import type { CallStatus, CallType, CallHistoryItem } from "@relay/contracts";

// ─────────────────────────────────────────────────────────────────────────────
// Durable call history (Postgres). The runtime (calls.runtime.ts) owns live
// state; this owns the permanent record. The row is created at call:init so a
// missed call survives a crash/disconnect/refresh. durationSec is computed by
// the service from the runtime answeredAt (connected media time only) and
// written once, at teardown.
// ─────────────────────────────────────────────────────────────────────────────

export class CallRepository {
  constructor(private fastify: FastifyInstance) {}

  // id is generated by the service so it can reserve the runtime slot
  // synchronously (before this await) and win the one-call-per-user race.
  async createRinging(input: {
    id:              string;
    callerId:        string;
    recipientId:     string;
    type:            CallType;
    conversationId?: string;
  }): Promise<void> {
    await this.fastify.prisma.call.create({
      data: {
        id:             input.id,
        callerId:       input.callerId,
        recipientId:    input.recipientId,
        type:           input.type,
        conversationId: input.conversationId ?? null,
        status:         "RINGING",
      },
      select: { id: true },
    });
  }

  async markAnswered(callId: string): Promise<void> {
    const now = new Date();
    await this.fastify.prisma.call.update({
      where: { id: callId },
      data:  { status: "ANSWERED", answeredAt: now, startedAt: now },
    });
  }

  // Terminal write. Called once from the service's terminate() routine.
  async markEnded(
    callId:        string,
    status:        CallStatus,
    durationSec:   number,
    endedByUserId?: string | null,
  ): Promise<void> {
    await this.fastify.prisma.call.update({
      where: { id: callId },
      data:  {
        status,
        durationSec,
        endedAt:       new Date(),
        endedByUserId: endedByUserId ?? null,
      },
    });
  }

  // Recent calls where the user is caller or recipient, newest first.
  async listForUser(userId: string, limit = 50): Promise<CallHistoryItem[]> {
    const rows = await this.fastify.prisma.call.findMany({
      where:   { OR: [{ callerId: userId }, { recipientId: userId }] },
      orderBy: { createdAt: "desc" },
      take:    limit,
      select: {
        id:          true,
        callerId:    true,
        type:        true,
        status:      true,
        durationSec: true,
        createdAt:   true,
        caller:      { select: { id: true, username: true } },
        recipient:   { select: { id: true, username: true } },
      },
    });

    return rows.map((r) => {
      const outgoing = r.callerId === userId;
      const other    = outgoing ? r.recipient : r.caller;
      return {
        id:          r.id,
        direction:   outgoing ? "outgoing" : "incoming",
        otherUser:   { id: other.id, username: other.username },
        type:        r.type as CallType,
        status:      r.status as CallStatus,
        durationSec: r.durationSec,
        createdAt:   r.createdAt.toISOString(),
      };
    });
  }
}
